projects:
  LasNotas:
    schemaPath: amplify/backend/api/LasNotas/build/schema.graphql
    includes:
      - src/module
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src
        region: us-east-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
